---
title: "Milestone 3"
author: "Miroslav Bergam"
date: "10/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)

#Importing tools like read_csv(), filter(), and count() from tidyverse package

library(tidyverse)

```

I retrieved the Spotify CSV data directly from Spotify's website, which allows one to download CSV 
files of its weekly, monthly, and yearly chart data. The file I added to this repository is data from a singular week. Billboard does not make it's data as easily accessible, therefore I retrieved this CSV file from a data.world user that compiled weekly chart data from 1958 to June, 2019. 

Thus far, I have stored the files in a directory labelled music-data. I will use these files or files from these sources if I make a visual on song positions, comparing how Spotify/streaming positions differ compared to their Billboard positions, which also factors in Youtube, iTunes, and physical sales. However, I may create a graphic that analyzes song sales by number and how streaming (specifically Spotify) has come to dominate the bulk of song data (over digital and physical copies). Because the two files in this repo lack the sales in numbers, I would have to scrape data from kworb.net, RIAA, and or nielson, if I choose to take my project in this direction.